export const SHOP = {
  name: "Roberts Garage",
  phone: "(832) 800-1351",
  phoneHref: "tel:+18328001351",
  smsHref: "sms:+18328001351",
  email: "robertsgarage21@gmail.com",
  emailHref: "mailto:robertsgarage21@gmail.com",
  address: "16120 Hwy 6, Rosharon, TX 77583",
  hours: "Mon–Fri 9 AM–6 PM · Sat 9 AM–4 PM · Sun Closed",
  hoursList: [
    { day: "Monday", time: "9 AM–6 PM" },
    { day: "Tuesday", time: "9 AM–6 PM" },
    { day: "Wednesday", time: "9 AM–6 PM" },
    { day: "Thursday", time: "9 AM–6 PM" },
    { day: "Friday", time: "9 AM–6 PM" },
    { day: "Saturday", time: "9 AM–4 PM" },
    { day: "Sunday", time: "Closed" },
  ],
  city: "Rosharon, Texas",
  mapsHref:
    "https://www.google.com/maps/search/?api=1&query=16120+Hwy+6+Rosharon+TX+77583",
  placeId: "ChIJ89NCeDLvQIYRLwziSZD_fCc",
  cid: "2881491375935753263",
  reviewsHref:
    "https://www.google.com/maps/place/?q=place_id:ChIJ89NCeDLvQIYRLwziSZD_fCc",
  writeReviewHref:
    "https://search.google.com/local/writereview?placeid=ChIJ89NCeDLvQIYRLwziSZD_fCc",
  services: [
    "Engine Diagnostics",
    "Fluid Services",
    "HVAC System",
    "Suspension & Steering",
    "Battery & Electrical",
    "Brake Service",
    "Tune Up",
    "Headlight Restoration",
  ],
  reviews: [
    {
      name: "DJ",
      rating: 5,
      text: "Hands down Robert's is the BEST auto shop I've ever been to. If you're looking for honest work, fast service, and people who actually care about your car, this is the spot.",
      vehicle: "Verified Customer",
    },
    {
      name: "Madeline Minor",
      rating: 5,
      text: "I found Rob on social media and definitely recommend him. He repaired my car very quickly and even checked a few days later to make sure how things were with it. His prices are reasonable and he does good work.",
      vehicle: "Verified Customer",
    },
    {
      name: "Brandea Brown",
      rating: 5,
      text: "Robert explained my concerns very well and gave his honest opinions and suggestions on the work that needed to be done. His prices were very reasonable and great service! I appreciate his flexibility over the weekend too.",
      vehicle: "Verified Customer",
    },
    {
      name: "Stephanie Du",
      rating: 5,
      text: "Fast, reliable and affordable! I had a quote from Honda for repairs/maintenance which cost around $2,700. Robert was able to do these repairs for half the cost!",
      vehicle: "Verified Customer",
    },
    {
      name: "Sherry Palmer",
      rating: 5,
      text: "So glad I found this hidden gem. Robert is an honest young man. Has very reasonable pricing. He knows what he's doing. I highly recommend. I'll be a customer for life.",
      vehicle: "Verified Customer",
    },
    {
      name: "Carolina Amet",
      rating: 5,
      text: "Great customer service. They take the time to explain what's going on with your vehicle and give you different options. They don't try to scam you with unnecessary services. I appreciate Rob's patience.",
      vehicle: "Verified Customer",
    },
  ],
};
