/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RaceRedRouteImport } from './routes/race-red'
import { Route as NeighborhoodRedRouteImport } from './routes/neighborhood-red'
import { Route as NeighborhoodDarkRouteImport } from './routes/neighborhood-dark'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'

const RaceRedRoute = RaceRedRouteImport.update({
  id: '/race-red',
  path: '/race-red',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodRedRoute = NeighborhoodRedRouteImport.update({
  id: '/neighborhood-red',
  path: '/neighborhood-red',
  getParentRoute: () => rootRouteImport,
} as any)
const NeighborhoodDarkRoute = NeighborhoodDarkRouteImport.update({
  id: '/neighborhood-dark',
  path: '/neighborhood-dark',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/neighborhood-dark': typeof NeighborhoodDarkRoute
  '/neighborhood-red': typeof NeighborhoodRedRoute
  '/race-red': typeof RaceRedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/neighborhood-dark': typeof NeighborhoodDarkRoute
  '/neighborhood-red': typeof NeighborhoodRedRoute
  '/race-red': typeof RaceRedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/neighborhood-dark': typeof NeighborhoodDarkRoute
  '/neighborhood-red': typeof NeighborhoodRedRoute
  '/race-red': typeof RaceRedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/neighborhood-dark'
    | '/neighborhood-red'
    | '/race-red'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/neighborhood-dark'
    | '/neighborhood-red'
    | '/race-red'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/neighborhood-dark'
    | '/neighborhood-red'
    | '/race-red'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  NeighborhoodDarkRoute: typeof NeighborhoodDarkRoute
  NeighborhoodRedRoute: typeof NeighborhoodRedRoute
  RaceRedRoute: typeof RaceRedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/race-red': {
      id: '/race-red'
      path: '/race-red'
      fullPath: '/race-red'
      preLoaderRoute: typeof RaceRedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhood-red': {
      id: '/neighborhood-red'
      path: '/neighborhood-red'
      fullPath: '/neighborhood-red'
      preLoaderRoute: typeof NeighborhoodRedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/neighborhood-dark': {
      id: '/neighborhood-dark'
      path: '/neighborhood-dark'
      fullPath: '/neighborhood-dark'
      preLoaderRoute: typeof NeighborhoodDarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  NeighborhoodDarkRoute: NeighborhoodDarkRoute,
  NeighborhoodRedRoute: NeighborhoodRedRoute,
  RaceRedRoute: RaceRedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
